name: Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    
jobs:   
  test:
    name: Test globalprogramlib in Linux / Mac OS / Windows
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: install dependencies
      run: pip install poetry --upgrade
    
    - name: install globalprogramlib
      run: poetry install 
    
    - name: test file formatting
      run: poetry run black --check globalprogramlib tests
      
    - name: test library
      run: poetry run pytest tests
    
    
  
  build:
    name: Build deploy package
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: install dependencies
      run: pip install poetry --upgrade
    
    - name: install globalprogramlib
      run: poetry install 
    
    - name: install globalprogramlib
      run: poetry build
      
    - uses: actions/upload-artifact@v2
      with:
        name: globalprogranlib main
        path: dist

